# Generated by Django 5.2.1 on 2025-06-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcollection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcollectionshare',
            name='perm_download',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
