# Generated by Django 5.0 on 2023-12-11 17:49

import baseweb.models
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.files.storage
import django.db.models.deletion
import django_extensions.db.fields
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPXFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(default=baseweb.models.generate_slug_token, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('wpt_options', models.JSONField(default=dict)),
                ('job_status', models.IntegerField(default=1)),
                ('delete_after', models.DateField()),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/jonas/entwicklung/gpx-viewer/gpxviewr/storage-fs')), upload_to='gpx_track/%Y/%m/%d/')),
            ],
            options={
                'ordering': ['name', '-created'],
            },
        ),
        migrations.CreateModel(
            name='GPXWayPointType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('gpx_sym_name', models.CharField(max_length=100)),
                ('osm_name', models.TextField(max_length=100)),
                ('osm_value', models.TextField(max_length=100)),
                ('osm_query_type', models.CharField(default='=', max_length=10)),
                ('around', models.IntegerField()),
                ('around_max', models.IntegerField()),
                ('around_duplicate', models.IntegerField(default=3000)),
                ('marker_filename', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPXTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('distance', models.FloatField()),
                ('gpx_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='baseweb.gpxfile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GPXTrackSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('number', models.IntegerField(default=0)),
                ('distance', models.FloatField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='baseweb.gpxtrack')),
            ],
            options={
                'ordering': ['track__name', 'number'],
            },
        ),
        migrations.CreateModel(
            name='GPXTrackSegmentPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('number', models.BigIntegerField(db_index=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326)),
                ('elevation', models.FloatField(null=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='baseweb.gpxtracksegment')),
            ],
            options={
                'ordering': ['segment__pk', 'number'],
            },
        ),
        migrations.CreateModel(
            name='GPXFileUserSegmentSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(null=True)),
                ('gpx_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_segments', to='baseweb.gpxfile')),
                ('point_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_splits_end', to='baseweb.gpxtracksegmentpoint')),
                ('point_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_splits_start', to='baseweb.gpxtracksegmentpoint')),
            ],
            options={
                'ordering': ['point_start__pk', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GPXTrackWayPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(default=dict)),
                ('hidden', models.BooleanField(default=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(db_index=True, default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326)),
                ('gpx_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='baseweb.gpxfile')),
                ('track_segment_point_nearby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='baseweb.gpxtracksegmentpoint')),
                ('waypoint_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='baseweb.gpxwaypointtype')),
            ],
            options={
                'ordering': ['track_segment_point_nearby__pk', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GPXTrackWayPointFromTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('geojson', models.JSONField(default=dict)),
                ('away_kilometer', models.FloatField(default=0.0)),
                ('waypoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='track_to_waypoint', to='baseweb.gpxtrackwaypoint')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
