# Generated by Django 4.2.7 on 2023-11-22 20:50

import baseweb.models
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPXTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(default=baseweb.models.generate_slug_token, editable=False)),
                ('name', models.TextField(max_length=100)),
                ('tracks', models.IntegerField(default=1)),
                ('wpt_options', models.JSONField(default=dict)),
                ('job_status', models.BooleanField(default=False)),
                ('delete_after', models.DateField()),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/jonas/entwicklung/gpx-viewer/gpxviewr/storage-fs')), upload_to='gpx_track/%Y/%m/%d/')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GPXWayPointType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('gpx_sym_name', models.CharField(max_length=100)),
                ('osm_name', models.TextField(max_length=100)),
                ('osm_value', models.TextField(max_length=100)),
                ('around', models.IntegerField()),
                ('around_max', models.IntegerField()),
                ('around_duplicate', models.IntegerField(default=3000)),
                ('marker_filename', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPXTrackWayPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(default=dict)),
                ('location', django.contrib.gis.db.models.fields.PointField(db_index=True, default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
                ('gpx_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='baseweb.gpxtrack')),
                ('waypoint_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='baseweb.gpxwaypointtype')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
