# Generated by Django 4.2.7 on 2023-11-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxtrack',
            name='job_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gpxtrack',
            name='wpt_options',
            field=models.JSONField(default=dict),
        ),
    ]
