# Generated by Django 5.2.1 on 2025-06-16 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseweb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxfile',
            name='perm_public_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gpxfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpx_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
