# Generated by Django 5.2.1 on 2025-06-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseweb', '0002_gpxfile_perm_public_available_gpxfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxwaypointtype',
            name='gpx_type_name',
            field=models.CharField(default='NO', max_length=100),
            preserve_default=False,
        ),
    ]
