# Generated by Django 4.2.7 on 2023-11-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseweb', '0002_gpxtrack_job_status_gpxtrack_wpt_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxwaypointtype',
            name='around_duplicate',
            field=models.IntegerField(default=3000),
        ),
    ]
