# Generated by Django 5.0.1 on 2024-01-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseweb', '0003_gpxtracksegment_total_ascent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxfileusersegmentsplit',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gpxfileusersegmentsplit',
            name='total_ascent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gpxfileusersegmentsplit',
            name='total_descent',
            field=models.FloatField(null=True),
        ),
    ]
