# Generated by Django 5.2.1 on 2025-06-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseweb', '0003_gpxwaypointtype_gpx_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxtrackwaypoint',
            name='bookmark',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
