# Generated by Django 5.0.3 on 2024-06-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseweb', '0004_gpxfileusersegmentsplit_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxwaypointtype',
            name='checked',
            field=models.BooleanField(default=True),
        ),
    ]
