# Generated by Django 5.2.2 on 2025-06-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseweb', '0004_gpxtrackwaypoint_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxwaypointtype',
            name='osmand_icon',
            field=models.CharField(default='shop', max_length=100),
            preserve_default=False,
        ),
    ]
