# Generated by Django 5.2 on 2025-04-11 17:31

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseweb', '0006_gpxtrack_link_alter_gpxfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxtracksegmentpoint',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpxfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/workspace/gpxviewr/storage-fs')), upload_to='gpx_track/%Y/%m/%d/'),
        ),
    ]
