# Generated by Django 5.2 on 2025-04-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseweb', '0007_gpxtracksegmentpoint_distance_alter_gpxfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpxfile',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
