# Generated by Django 5.2 on 2025-04-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseweb', '0008_alter_gpxfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxwaypointtype',
            name='generate_track_to_waypoint',
            field=models.BooleanField(default=False),
        ),
    ]
