# Generated by Django 5.2 on 2025-05-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseweb', '0009_gpxwaypointtype_generate_track_to_waypoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxwaypointtype',
            name='osm_extra_query',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
